
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
#hola mundoooooo
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
print("hola mundo, sin proyecto")
#git remote add origin https://github.com/egomex/Facturaci-n.git
#Permite sincronizar el git con el github

#COMANDOS DE GIT
#git init
#git add README.md
#git commit -m "first commit"
#git status
# git branch -M main
#git push -u origin main

# pra hacer un cambio, primero hay que poner: git add, git commit y git push